version: '3'
services:
  express-app:
    image: node:14
    container_name: express-app
    working_dir: /app
    volumes:
      - ./your-express-app-directory:/app
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/your-database-name
    depends_on:
      - mongo
    command: 'npm start'

  mongo:
    image: mongo:4.4
    container_name: mongo
    volumes:
      - ./mongo-data:/data/db
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=your-database-name
